apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ewps-static.fullname" . }}
  labels:
    {{- include "ewps-static.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ewps-static.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ewps-static.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-nfs"
      serviceAccountName: {{ include "ewps-static.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: nfs-pvc
              mountPath: "/usr/share/nginx/html"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
              tcpSocket:
                port: 80
              initialDelaySeconds: 15
              periodSeconds: 20
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
