apiVersion: v1
kind: Service
metadata:
  name: {{ include "ewps-static.fullname" . }}
  labels:
    {{- include "ewps-static.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Release.Name }}-dta
  selector:
    {{- include "ewps-static.selectorLabels" . | nindent 4 }}
