{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ogc-pilot-ewps.fullname" . -}}

{{- $defaultServicePort := printf "%s-%s" .Release.Name "wps" -}}
{{- $ewpsStaticName := printf "%s-%s" .Release.Name "ewps-static" -}}
{{- $ewpsStaticPortName := printf "%s-%s" .Release.Name "dta" -}}

{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ogc-pilot-ewps.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/data/"
            backend:
              serviceName: {{ $ewpsStaticName | quote }}
              servicePort: {{ $ewpsStaticPortName | quote }}
          - path: "/"
            backend:
              serviceName: {{ $fullName | quote }}
              servicePort: {{ $defaultServicePort | quote }}

{{- end }}
