{{- if .Values.rbac.create -}}
{{- $serviceName := include "ogc-pilot-ewps.fullname" . -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $serviceName }}-schedule-jobs
  namespace: {{ .ewpsKubernetesNamespace | default .Release.Namespace }}
  labels:
    "app.kubernetes.io/name": '{{ template "ogc-pilot-ewps.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "persistentvolumeclaims"]
    verbs: ["create", "delete", "deletecollection", "patch", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceName }}-schedule-jobs
  namespace: {{ .ewpsKubernetesNamespace | default .Release.Namespace }}
  labels:
    "app.kubernetes.io/name": '{{ template "ogc-pilot-ewps.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $serviceName }}-schedule-jobs
subjects:
  - kind: ServiceAccount
    name: {{ include "ogc-pilot-ewps.serviceAccountName" . }}
    namespace: {{ .ewpsKubernetesNamespace | default .Release.Namespace }}

{{- end -}}
